### ISSUE TITLE
Failed to run the code!!

### ISSUE THREAD

**Issue by KesonStar** [lukasuz/Articulated-Point-NeRF#2]
Hello! Thanks for your work!

When I'm trying to train backbone & PCD representation, I'll always meet such errors and warnings without changing any codes:
1. A runtime warning from numpy during the process of training:
```
root/miniconda3/envs/Articulated-Point-NeRF/lib/python3.9/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value enco
untered in scalar divide                                                                                                               
  ret = ret.dtype.type(ret / rcount) 
``` 

2. A value error when creating the skeletons:
```
Traceback (most recent call last):
  File "/data/new_disk4/Keson/test/Articulated-Point-NeRF/run.py", line 1269, in <module>
    train(args, cfg, read_path, save_path, data_dict = data_dict, stages=stages)
  File "/data/new_disk4/Keson/test/Articulated-Point-NeRF/run.py", line 1066, in train
    export_point_cloud(model, data_dict, read_path, render_viewpoints_kwargs, canonical_t, pcd_density_threshold,
  File "/data/new_disk4/Keson/test/Articulated-Point-NeRF/run.py", line 1233, in export_point_cloud
    res = create_skeleton(binary_volume, grid_xyz, bone_length=bone_length)
  File "/data/new_disk4/Keson/test/Articulated-Point-NeRF/skeletonizer.py", line 256, in create_skeleton
    root_indx = D.sum(1).argmin()
ValueError: attempt to get argmin of an empty sequence
```

I guess it's about the version of libs in my environment that affects. May you please show more detailed information of version of the libs and your environment?

**Comment by KesonStar** [comment]
Fixed. It's about the output of skeletonize from the `skimage`, which is true instead of 255 here due to the version.
